apiVersion: v1
kind: Namespace
metadata:
  name: kunde-beispiel
  labels:
    # Label für Flux Auto-Sync
    app.kubernetes.io/created-by: platform-team
    app.kubernetes.io/managed-by: flux
    # Tenant Label für RBAC und NetworkPolicies
    idp-platform.io/tenant: kunde-beispiel
    idp-platform.io/environment: production
